Added Hand class -JT
jnguyen7410/DD-Blackjack pull request #6
Opened 2019-02-14 03:56 UTC by jtamayo0701

Check out this dope ass Hand class

2019-02-14 04:45 UTC, jurytan requested changes
Good job so far. Please make the changes I requested.

2019-02-14 04:45 UTC, jnguyen7410 commented on Hand.java
> +    List <Card> currentCards = new ArrayList<Card>();
nit: List<Card>

2019-02-14 04:45 UTC, jnguyen7410 commented on Hand.java
> +    List <Card> currentCards = new ArrayList<Card>();
Also, do the init in the constructor

2019-02-14 04:45 UTC, jnguyen7410 commented on Hand.java
> +        Card randomCard2 = new Card();
Remove these.

2019-02-14 04:45 UTC, jnguyen7410 commented on Hand.java
> +        currentCards.add(randomCard2); //Add the second card
Remove these as well.

2019-02-14 04:45 UTC, jnguyen7410 commented on Hand.java
> +        Card randomCard2 = new Card();
Move the init from the field to here.

2019-02-14 04:45 UTC, jnguyen7410 commented on Hand.java
> +
Add a function to calculate the hand score

2019-02-14 04:45 UTC, jnguyen7410 commented on Hand.java
> +    public void revealCards()
Overload this function to have an argument with a List of Card

2019-02-14 04:45 UTC, jnguyen7410 commented on Hand.java
> +    public void addCards()
There's no arguments. Please add List<Card> as arg

2019-02-28 02:52 UTC, jtamayo0701 commented on Hand.java
> +    public void addCards()
I have included the List as arg

2019-02-28 02:52 UTC, jtamayo0701 commented on Hand.java
> +    public void addCards()
Please see Hand Class v2

2019-02-28 03:25 UTC, jtamayo0701 commented on Hand.java
> +    public void revealCards()
I have included the List as arg. 
Please see Hand Class v2

2019-02-28 03:27 UTC, jtamayo0701 commented on Hand.java
> +
Added the calculateHandScore function.

2019-02-28 03:28 UTC, jtamayo0701 commented on Hand.java
> +        currentCards.add(randomCard2); //Add the second card
Deleted these.

2019-02-28 03:30 UTC, jtamayo0701 commented on Hand.java
> +        Card randomCard2 = new Card();
Deleted it and moved the init within the constructor.

2019-02-28 03:30 UTC, jtamayo0701 commented on Hand.java
> +    List <Card> currentCards = new ArrayList<Card>();
Moved the init to the constructor.

2019-02-28 03:33 UTC, jtamayo0701 commented
@jnguyen7410 I made the update to my code.

2019-02-28 04:41 UTC, jnguyen7410 commented
lgtm

2019-02-28 04:42 UTC, jurytan approved these changes

2019-02-28 04:43 UTC, merged